### ISSUE TITLE
Doesn't compile on linux, can't find glpk.h

### ISSUE THREAD

**Issue by Astlaan** [QE-Lab/OpenQL#253] opened 2019-11-10 17:49 UTC
Hello,

I tried to compile OpenQL on a linux machine. I cloned the repository, checked out mapper (tried with develop too), ran `cmake ..` (which went without problems), but when running make I got:

![image](https://user-images.githubusercontent.com/10374970/68548141-fb80b180-03e9-11ea-8004-ed6bd0f54f66.png)

I confirmed I have all the necessary requirements

![image](https://user-images.githubusercontent.com/10374970/68548167-2ff46d80-03ea-11ea-82bc-d9eb2cddf5ce.png)

The weird thing is that `glpk.h` is indeed in the same folder as `glpk.cc`.
Running `ll` on `deps/lemon/lemon`, I indeed have:

![image](https://user-images.githubusercontent.com/10374970/68548228-c9238400-03ea-11ea-8feb-c1cba0797829.png)

**Comment by imranashraf** [comment] 2019-11-12 04:46
@jvansomeren can you please look why this installation is failing?

**Comment by jvansomeren** [comment] 2019-11-12 09:14
Hi Diogo,
I cannot reproduce this in the develop branch.
I did a fresh pull, mkdir cbuild, cd cbuild, cmake .., make 
See the logs of this.
I also don't see the comments of the compiler on the register keyword use in random.cc,
so there definitely is something different.
Best, Hans

Here is the cmake:

![cmake-log](https://user-images.githubusercontent.com/17248438/68657986-ed8b7780-0534-11ea-9a02-07af9d056546.png)

And then the first part of the make:

![make-log1](https://user-images.githubusercontent.com/17248438/68658011-fa0fd000-0534-11ea-8b84-a765b08cda66.png)

and then the last part of the make:

![make-log2](https://user-images.githubusercontent.com/17248438/68658042-0562fb80-0535-11ea-837b-79547e2c5af7.png)

Please do the same at your side and check the differences.

**Comment by Astlaan** [comment] 2019-11-12 13:15
I freshly reinstalled C, C++ and make (from anaconda) and still have the same problem.
There was only one difference I could see: in Hans cmake, ghostscript was detected, while in mine it was not, but I installed it and the problem persists...

My `cmake` is now identical, while in my `make `the error appears right in the beginning.

This is the output of `cmake ..`:
![image](https://user-images.githubusercontent.com/10374970/68674369-09ebdc00-0556-11ea-89d5-0f7203daa6a4.png)
![image](https://user-images.githubusercontent.com/10374970/68674395-16703480-0556-11ea-865b-dbff3113bd08.png)
![image](https://user-images.githubusercontent.com/10374970/68674475-3c95d480-0556-11ea-86ff-4be63107509d.png)


And this is the output of `make`:
![image](https://user-images.githubusercontent.com/10374970/68674531-56cfb280-0556-11ea-97a1-b79f2d3fb6f5.png)
![image](https://user-images.githubusercontent.com/10374970/68674618-7bc42580-0556-11ea-84b5-ce4fe29e4fe7.png)

**Comment by imranashraf** [comment] 2020-03-18 17:23
mapper is now merged to develop. since it can be built by Travis CI and wheels are also availabe, this problem should be resolved, right @Astlaan ?

**Closed** 2020-03-23 05:58 UTC
