### ISSUE TITLE
Pre-build binaries for OpenQL

### ISSUE THREAD

**Issue by AdriaanRol** [QE-Lab/OpenQL#241] opened 2019-07-17 09:14 UTC
@imranashraf , we are still facing a lot of issues with installing OpenQL. Mostly on windows but also on mac. 

The core problem here is that successful installation of OpenQL requires the right versions of different compilers and python to work together. Installing OpenQL should be as simple as `pip install openql`, not requiring cloning the repository. Making this installation that simple would involve two steps 

1. creating a binary wheel distribution 
2. uploading the distribution to PyPi

## Creating a binary distribution wheel 
In order to be able to do `pip install openql` without needing to configure the compilers, we need to provide precompiled binaries. Once you are able to compile on a (windows) system this is actually quite trivial. 

The single line `python setup.py sdist bdist_wheel` does exactly this. It runs setup.py like we already do but also creates several files in  `OpenQL/dist/`. These files are `openql-0.7.0-py3-none-any.whl` and `openql-0.7.0.tar.gz`.  

A precompiled binary should be enough to run it on any other system (of the same OS and python version) and is enough to upload the package to `PyPI`, the standard python package manager. 

Details are described here: 
https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

Since we already test if it is possible to compile on different systems I think providing the wheel package is a natural thing to do as well. Especially as it saves us major problems on the DCL side in deploying this to our setups. 

Just having the wheel image available with every release is a big improvement for us. You can either attach this to the release on github or upload this to PyPI. 

## Releasing on PyPI 
The details of uploading a package to PyPI can be found here: https://packaging.python.org/tutorials/packaging-projects/ 

Most of these details involve setting up the setup.py file and creating the wheel. Steps we have already done. 

## What about Conda? 
I know that I have previously promoted using conda for this. The idea would be to use conda install for installing the package. This idea still holds although we have since moved from using conda as our package manager to using pipenv (based on pip). However, the build-recipe provided right now still tries to do the compilation on the host pc (and tries to solve the environment to allow this). Besides, the conda-built recipe does not work #240 , at least on my system. 

@imranashraf Let me know if it is possible to do these things as it is quite important for the usability in our lab to have an easy installation and upgrade path for OpenQL.

**Comment by MiguelSMoreira** [comment] 2019-07-17 09:19
@AdriaanRol @imranashraf 

I can attest that having such a functionality would greatly facilitate our work here at the lab. I have also been running at problems compiling OpenQL on my system; distributing pre-compiled binaries, I believe, would solve this!

**Comment by imranashraf** [comment] 2019-07-18 08:06
@AdriaanRol I am having a look at it. I dont see any problem and it should definitely be possible.

**Comment by imranashraf** [comment] 2019-07-22 12:23
@AdriaanRol and @MiguelSMoreira i have created python wheels for openql version 0.7.0 for win, linux and mac which can be found in the release section for now:
https://github.com/QE-Lab/OpenQL/releases/tag/0.7.0

can you please verify if you can install openql on your systems by using corresponding wheel?

**Comment by AdriaanRol** [comment] 2019-07-23 07:39
Great, I'll take a look  at them.

**Comment by nyxus** [comment] 2019-08-15 13:09
I've tried to install the openQL 0.7.0 wheel package from the (releases)[https://github.com/QE-Lab/OpenQL/releases/tag/0.7.0] as provided by @imranashraf. But unfortunately, the package is built for python3.7 while our systems (at DCL) still run on python3.6. I've tried to upgrade one of the systems to 3.7 but run into some issues with other packages. I could successfully install and import the openQL package but was not able to successfully run our tests. The tests failing have to do with the upgrade to 3.7 and (other) packages. So, for now, I cannot confirm that the openQL 0.7.0 wheel package is working.

**Comment by imranashraf** [comment] 2019-08-28 02:58
@nyxus kindly check the updated [wheel](https://github.com/QE-Lab/OpenQL/releases/download/0.7.0/openql-0.7.0-py3-none-win_amd64.whl) in the releases.

**Comment by nyxus** [comment] 2019-08-28 08:06
@imranashraf, thanks! Will check the wheel packages this afternoon!

**Comment by nyxus** [comment] 2019-08-28 12:06
@imranashraf, I've tried to test the packages but still got the error that the package is built for python3.7. 

```powershell
C:\Users\TUD277871 PS>pip install https://github.com/QE-Lab/OpenQL/releases/download/0.7.0/openql-0.7.0-py3-none-win_amd64.whl
Collecting openql==0.7.0 from https://github.com/QE-Lab/OpenQL/releases/download/0.7.0/openql-0.7.0-py3-none-win_amd64.whl
  Downloading https://github.com/QE-Lab/OpenQL/releases/download/0.7.0/openql-0.7.0-py3-none-win_amd64.whl (570kB)
     |████████████████████████████████| 573kB 595kB/s
Installing collected packages: openql
Successfully installed openql-0.7.0
C:\Users\TUD277871 PS>ipython.exe
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import openql
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\site-packages\openql\openql.py in swig_import_helper()
     16         try:
---> 17             return importlib.import_module(mname)
     18         except ImportError:

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap.py in _load_unlocked(spec)

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap.py in module_from_spec(spec)

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap_external.py in create_module(self, spec)

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: Module use of python37.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3b1d02f2b85b> in <module>
----> 1 import openql

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\site-packages\openql\__init__.py in <module>
     15
     16 if PY3:
---> 17     from .openql import Program, Kernel
     18 else:
     19     from openql import *

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\site-packages\openql\openql.py in <module>
     18         except ImportError:
     19             return importlib.import_module('_openql')
---> 20     _openql = swig_import_helper()
     21     del swig_import_helper
     22 elif _swig_python_version_info >= (2, 6, 0):

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\site-packages\openql\openql.py in swig_import_helper()
     17             return importlib.import_module(mname)
     18         except ImportError:
---> 19             return importlib.import_module('_openql')
     20     _openql = swig_import_helper()
     21     del swig_import_helper

c:\users\tud277871\.virtualenvs\userenv-ghejxth9\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127
    128

ModuleNotFoundError: No module named '_openql'
```
Note the error `ImportError: Module use of python37.dll conflicts with this version of Python.`

**Comment by nyxus** [comment] 2019-08-30 09:05
I think the problem is that the 0.7.0 release does not include PR https://github.com/QE-Lab/OpenQL/pull/242. Because when I try to directly install openQL directly from the repo:  
`pip install git+https://github.com/QE-Lab/OpenQL.git@0.7.0` the same problem occurs.

**Comment by imranashraf** [comment] 2019-11-02 05:05
Release 0.8.0 contains wheels for Linux, windows and OSX. closing this issue

**Closed by imranashraf** 2019-11-02 05:05 UTC
Labels: enhancement, prio: high
